version: '2'

services:
  influxdb:
    image: influxdb:1.2.0-alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - /etc/letsencrypt:/etc/letsencrypt
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    links:
      - grafana
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
