version: '2'

services:
  influxdb:
    image: influxdb:1.2.0-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
